### ISSUE TITLE
[Melhoria / Documentação] Incluir a versão do Node.js utilizada no projeto

### ISSUE THREAD

**Issue by emerson-oliveira** [Luizboaventura1/fastdevelopment#1]
## Descrição

Para facilitar a contribuição de outros desenvolvedores ao projeto, sugiro a adição de um arquivo .nvmrc. Este arquivo especificará a versão do Node.js que o projeto está utilizando, permitindo que qualquer pessoa que clone o repositório possa facilmente alternar para a versão correta do Node.js.

Isso é especialmente útil para projetos que podem não ser compatíveis com todas as versões do Node.js. Ao incluir um arquivo .nvmrc, podemos garantir que todos os contribuidores estejam usando a mesma versão do Node.js, minimizando assim os problemas de compatibilidade.

Para mais informações sobre como criar um arquivo .nvmrc, consulte esta referência.

## Execução

- [x] Adicione o arquivo .nvmrc

**Comment by Luizboaventura1** [comment]
Arquivo adicionado
