### ISSUE TITLE
[Melhoria / Documentação] Implementar Milestones e Issues Associadas

### ISSUE THREAD

**Issue by emerson-oliveira** [Luizboaventura1/fastdevelopment#2]
## Descrição:

Para melhorar a organização do projeto e facilitar a contribuição de outros desenvolvedores, sugiro a implementação de Milestones. As **Milestones** podem ser usadas para dividir o projeto em etapas distintas, cada uma com seus próprios objetivos e prazos.

Além disso, dentro de cada Milestone, podemos criar **Issues** específicas que precisam ser resolvidas. Essas Issues representarão as tarefas que desejamos executar durante cada etapa do projeto.

Ao adotar essa estrutura, podemos tornar o processo de desenvolvimento mais transparente e eficiente. Isso também permitirá que os contribuidores vejam claramente o que precisa ser feito e quando, facilitando a colaboração e a contribuição para o projeto.

**Comment by Luizboaventura1** [comment]
Obrigado pelo feedback, vou trabalhar nisso pra facilitar as contribuições.
