### ISSUE TITLE
[Melhoria / Documentação]  Atualizar o Guia do Usuário para Resolver o Erro de Instalação do Firebase

### ISSUE THREAD

**Issue by emerson-oliveira** [Luizboaventura1/fastdevelopment#3]
## Descrição:

Ao seguir as instruções atuais para a instalação do projeto, encontrei um problema. Especificamente, recebo um erro 500 do Firebase que diz `Error (auth/invalid-api-key)`.

Isso sugere que a chave da API fornecida para o Firebase é inválida. Este problema impede a instalação bem-sucedida e a execução do projeto.

Solicito que o guia do usuário seja atualizado para resolver esse problema. Isso pode envolver a correção da chave da API do Firebase ou a atualização das instruções de instalação para garantir que a chave correta seja usada.

**Comment by Luizboaventura1** [comment]
O problema é que para ser usado precisa da chave de api que esta no arquivo .env, vou tentar fazer com que aplicação funcione sem precisar ter as chaves de api, e assim qualquer pessoa vai poder contribuir

**Comment by emerson-oliveira** [comment]
Caso queira deixar as issues em aberto, posso ir te ajudando na construção e revisando o código que está sendo feito.

**Comment by Luizboaventura1** [comment]
Boa sugestão, vou considerar usar o SQLite pro desenvolvimento local, mas antes vou arrumar essa parte das documentações e depois dar uma estudada nele já que nunca usei.

**Comment by Luizboaventura1** [comment]
Guia de contribuição criado: https://github.com/Luizboaventura1/fastdevelopment/blob/main/docs/developer-guide/pt-br/estrutura.md
